import {introductionFromBody,writingStats} from './writing-utils.js';
import {database,el,safeImage} from './shared.js';
import {member,profile,googleSignIn,requireMember} from './member-auth.js?v=20261007-profile4';
const notice=document.querySelector('#notice'),editor=document.querySelector('#editor'),status=document.querySelector('#editor-status'),signout=document.querySelector('#signout');let db,user,me,articles=[],dirty=false;
const field=n=>editor.elements.namedItem(n);function syncStats(){const counter=document.querySelector('#word-count');if(counter){const stats=writingStats(field('body').value);counter.textContent=stats.words+' words · '+stats.minutes+' min read';}}editor.oninput=()=>{dirty=true;syncStats();};
function showPublished(article,updated){
 const dialog=el('dialog',undefined,'publish-confirmation'),heading=el('h2',updated?'Your journal is updated!':'Your journal is published!');heading.id='publish-confirmation-title';dialog.setAttribute('aria-labelledby',heading.id);
 const check=el('div','✓','publish-success-icon');check.setAttribute('aria-hidden','true');const title=el('p',article.title,'publish-story-title'),message=el('p','Your journal is now public. Readers can read, like, and comment.','hint'),actions=el('div',undefined,'actions'),read=el('a','Read my journal','primary'),another=el('button','Write another'),close=el('button','Continue editing','publish-close');
 read.href='./?article='+encodeURIComponent(article.id);another.type=close.type='button';another.onclick=()=>{dialog.close();reset();field('title').focus();};close.onclick=()=>dialog.close();actions.append(read,another);dialog.append(check,heading,title,message,actions,close);document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove(),{once:true});dialog.showModal();
}
function reset(){editor.reset();field('id').value='';dirty=false;status.textContent='';editor.querySelector('[value="publish"]').textContent='Publish journal';syncStats();}
function edit(a){if(dirty&&!confirm('Discard your unsaved changes?'))return;if(field('category').tagName==='SELECT'&&a.category&&![...field('category').options].some(o=>o.value===a.category)){const option=el('option',a.category);option.value=a.category;field('category').append(option);}for(const key of ['id','title','category','excerpt','cover_url','body'])field(key).value=a[key]||'';syncStats();dirty=false;editor.querySelector('[value="publish"]').textContent=a.status==='published'?'Update published journal':'Publish journal';status.textContent=a.status==='published'?'Published · Saving as a draft unpublishes this journal.':'Draft';editor.scrollIntoView({behavior:'smooth'});}
async function load(){const {data,error}=await db.from('articles').select('*').eq('owner_id',user.id).order('created_at',{ascending:false});if(error)throw error;articles=data;const list=document.querySelector('#list');list.replaceChildren();if(!data.length)list.append(el('p','Your first story starts here.'));for(const a of data){const row=el('div',undefined,'article-list-item');row.append(el('strong',a.title),el('small',a.status));const actions=el('div',undefined,'article-list-actions');const button=el('button','Edit');button.onclick=()=>edit(a);const remove=el('button','Delete','danger');remove.onclick=async()=>{if(!confirm('Permanently delete this journal and its comments?'))return;remove.disabled=true;try{await requireMember();const {error}=await db.from('articles').delete().eq('id',a.id).eq('owner_id',user.id).select('id').single();if(error)throw error;if(field('id').value===a.id)reset();await load();}catch(err){notice.textContent=err.message;}finally{remove.disabled=false;}};actions.append(button,remove);if(a.status==='published'){const view=el('a','View / comments','article-view');view.href='./?article='+a.id;actions.append(view);}row.append(actions);list.append(row);}}
document.querySelector('#google').onclick=async()=>{try{await googleSignIn();}catch(err){notice.textContent=err.message;}};
if(signout)signout.onclick=async()=>{await db.auth.signOut();location.reload();};document.querySelector('#new').onclick=()=>{if(!dirty||confirm('Discard your unsaved changes?'))reset();};
editor.onsubmit=async e=>{e.preventDefault();const buttons=[...editor.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await requireMember();me=await profile();const id=field('id').value,existing=articles.find(a=>a.id===id),published=e.submitter?.value==='publish';const payload={author:me.display_name};for(const key of ['title','category','excerpt','cover_url','body'])payload[key]=field(key).value.trim();payload.category=payload.category||'Personal reflections';payload.excerpt=payload.excerpt||introductionFromBody(payload.body);if(['title','body'].some(key=>!payload[key]))throw Error('Add a title and write your story.');if(payload.cover_url&&!safeImage(payload.cover_url))throw Error('Use an HTTPS cover URL.');payload.status=published?'published':'draft';payload.published_at=published?(existing?.published_at||new Date().toISOString()):null;const query=id?db.from('articles').update(payload).eq('id',id).eq('owner_id',user.id):db.from('articles').insert(payload);const {data,error}=await query.select().single();if(error)throw error;field('id').value=data.id;dirty=false;try{await load();}catch{notice.textContent='Your journal was saved, but the journal list could not refresh.';}if(published)showPublished(data,existing?.status==='published');status.textContent=published?'Published. Everyone can read your journal now.':'Draft saved.';editor.querySelector('[value="publish"]').textContent=published?'Update published journal':'Publish journal';}catch(err){status.textContent=err.message;}finally{buttons.forEach(b=>b.disabled=false);}};
try{const oauthError=new URLSearchParams(location.hash.slice(1)).get('error_description');if(oauthError)throw Error(oauthError);db=await database();user=await member();if(user){let loginReturn=Boolean(window.JOURNAL_LOGIN_RETURN);try{loginReturn=loginReturn||sessionStorage.getItem('journal-login-profile')==='1';}catch{}if(loginReturn){await profile();try{sessionStorage.removeItem('journal-login-profile');}catch{}location.replace('profile.html?user='+encodeURIComponent(user.id));}else{me=await profile();document.querySelector('#signin').hidden=true;document.querySelector('#member-space').hidden=false;if(signout)signout.hidden=false;notice.textContent='';await load();}}else{location.replace('login.html');}}catch(err){notice.textContent=err.message;}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});







