import {avatar} from './social.js';
import {database,el,safeImage} from './shared.js';
import {member,profile,googleSignIn,requireMember} from './member-auth.js';
const notice=document.querySelector('#notice'),editor=document.querySelector('#editor'),status=document.querySelector('#editor-status'),pf=document.querySelector('#profile-form');let db,user,me,articles=[],dirty=false;
const field=n=>editor.elements.namedItem(n);editor.oninput=()=>dirty=true;
function reset(){editor.reset();field('id').value='';dirty=false;status.textContent='';editor.querySelector('[value="publish"]').textContent='Publish journal';}
function edit(a){if(dirty&&!confirm('Discard your unsaved changes?'))return;for(const key of ['id','title','category','excerpt','cover_url','body'])field(key).value=a[key]||'';dirty=false;editor.querySelector('[value="publish"]').textContent=a.status==='published'?'Update published journal':'Publish journal';status.textContent=a.status==='published'?'Published · Saving as a draft unpublishes this journal.':'Draft';editor.scrollIntoView({behavior:'smooth'});}
async function load(){const {data,error}=await db.from('articles').select('*').eq('owner_id',user.id).order('created_at',{ascending:false});if(error)throw error;articles=data;const list=document.querySelector('#list');list.replaceChildren();if(!data.length)list.append(el('p','Your first story starts here.'));for(const a of data){const row=el('div',undefined,'article-list-item');row.append(el('strong',a.title),el('small',a.status));const actions=el('div',undefined,'article-list-actions');const button=el('button','Edit');button.onclick=()=>edit(a);const remove=el('button','Delete','danger');remove.onclick=async()=>{if(!confirm('Permanently delete this journal and its comments?'))return;remove.disabled=true;try{await requireMember();const {error}=await db.from('articles').delete().eq('id',a.id).eq('owner_id',user.id).select('id').single();if(error)throw error;if(field('id').value===a.id)reset();await load();}catch(err){notice.textContent=err.message;}finally{remove.disabled=false;}};actions.append(button,remove);if(a.status==='published'){const view=el('a','View / comments','article-view');view.href='./?article='+a.id;actions.append(view);}row.append(actions);list.append(row);}}
document.querySelector('#google').onclick=async()=>{try{await googleSignIn();}catch(err){notice.textContent=err.message;}};
document.querySelector('#signout').onclick=async()=>{await db.auth.signOut();location.reload();};document.querySelector('#new').onclick=()=>{if(!dirty||confirm('Discard your unsaved changes?'))reset();};
pf.onsubmit=async e=>{e.preventDefault();const button=pf.querySelector('button');button.disabled=true;try{await requireMember();const payload={display_name:pf.elements.display_name.value.trim(),bio:pf.elements.bio.value.trim(),avatar_url:pf.elements.avatar_url.value.trim()};if(!payload.display_name)throw Error('Enter your name.');if(payload.avatar_url&&!safeImage(payload.avatar_url))throw Error('Use an HTTPS photo URL.');const {error}=await db.from('profiles').update(payload).eq('id',user.id).select('id').single();if(error)throw error;me={...me,...payload};showAvatar();notice.textContent='Profile saved.';}catch(err){notice.textContent=err.message;}finally{button.disabled=false;}};
editor.onsubmit=async e=>{e.preventDefault();const buttons=[...editor.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await requireMember();me=await profile();const id=field('id').value,existing=articles.find(a=>a.id===id),published=e.submitter?.value==='publish';const payload={author:me.display_name};for(const key of ['title','category','excerpt','cover_url','body'])payload[key]=field(key).value.trim();if(['title','category','excerpt','body'].some(key=>!payload[key]))throw Error('Fill in the journal fields.');if(payload.cover_url&&!safeImage(payload.cover_url))throw Error('Use an HTTPS cover URL.');payload.status=published?'published':'draft';payload.published_at=published?(existing?.published_at||new Date().toISOString()):null;const query=id?db.from('articles').update(payload).eq('id',id).eq('owner_id',user.id):db.from('articles').insert(payload);const {data,error}=await query.select().single();if(error)throw error;field('id').value=data.id;dirty=false;await load();status.textContent=published?'Published. Everyone can read your journal now.':'Draft saved.';editor.querySelector('[value="publish"]').textContent=published?'Update published journal':'Publish journal';}catch(err){status.textContent=err.message;}finally{buttons.forEach(b=>b.disabled=false);}};
try{const oauthError=new URLSearchParams(location.hash.slice(1)).get('error_description');if(oauthError)throw Error(oauthError);db=await database();user=await member();if(user){me=await profile();document.querySelector('#signin').hidden=true;document.querySelector('#member-space').hidden=false;document.querySelector('#signout').hidden=false;for(const key of ['display_name','avatar_url','bio'])pf.elements[key].value=me[key]||'';document.querySelector('#profile-link').href='profile.html?user='+user.id;showAvatar();await load();}}catch(err){notice.textContent=err.message;}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});

function showAvatar(){let slot=document.querySelector('#my-avatar');if(!slot){slot=el('div');slot.id='my-avatar';pf.prepend(slot);}slot.replaceChildren(avatar(me.display_name,me.avatar_url,'avatar-large'));}
