import {database,el,cover} from './shared.js';
import {avatar} from './social.js?v=20261008-heart1';
import {member,requireMember} from './member-auth.js';
import {contestState,contestDate,communityWinners} from './contest-utils.js';
const notice=document.querySelector('#contest-notice'),area=document.querySelector('#contest-content');
try{const db=await database(),id=new URLSearchParams(location.search).get('id');let query=db.from('writing_contests').select('*');query=id?query.eq('id',id):query.order('created_at',{ascending:false}).limit(1);const result=await query;if(result.error)throw result.error;const c=result.data[0];if(!c){notice.textContent='No contest is currently available.';}else{
 document.title=c.title+' — TheCommonJournal';let viewer=await member().catch(()=>null),mine=null,rows=[];const intro=el('section',undefined,'contest-intro'),trophy=el('span','🏆','contest-trophy');trophy.setAttribute('aria-hidden','true');intro.append(trophy,el('span','WEEKLY WRITING CONTEST','contest-badge'),el('h1',c.title),el('p',c.description),el('p','Languages: '+c.languages),el('p','Entries close '+contestDate(c.entries_close)+' · Voting closes '+contestDate(c.voting_close),'hint'));const rules=el('details',undefined,'contest-rules');rules.append(el('summary','Contest rules'),el('p',c.rules||'Submit one original published journal of your own. One vote per signed-in account; your vote can change until voting closes. Journals remain public after the contest.'),el('p','Recognition: '+c.recognition));intro.append(rules);area.append(intro);
 const entrySection=el('section',undefined,'contest-enter'),entryStatus=el('p','','hint');entryStatus.setAttribute('role','status');const entryButton=el('button','Enter contest','primary');entryButton.type='button';const entryForm=el('form');entryForm.hidden=true;const choiceLabel=el('label','Choose your published journal'),choice=el('select');choice.required=true;choiceLabel.append(choice);const submit=el('button','Submit entry','primary'),write=el('a','Write a new journal','article-view');write.href='account.html';submit.type='submit';entryForm.append(choiceLabel,el('p','Your journal will also remain in the regular feed. One entry per writer.','hint'),submit,write);entrySection.append(entryButton,entryForm,entryStatus);area.append(entrySection);
 entryButton.onclick=async()=>{if(!viewer){location.href='login.html';return;}entryButton.disabled=true;try{await requireMember();const r=await db.from('articles').select('id,title').eq('owner_id',viewer.id).eq('status','published').order('published_at',{ascending:false});if(r.error)throw r.error;choice.replaceChildren();for(const a of r.data){const o=el('option',a.title);o.value=a.id;choice.append(o);}if(!r.data.length){entryStatus.replaceChildren(el('span','Publish a journal first. '));const link=el('a','Write a journal','article-view');link.href='account.html';entryStatus.append(link);}else entryForm.hidden=false;}catch(err){entryStatus.textContent=err.message;}finally{entryButton.disabled=false;}};
 entryForm.onsubmit=async e=>{e.preventDefault();submit.disabled=true;try{await requireMember();const r=await db.rpc('enter_writing_contest',{target_contest:c.id,target_article:choice.value});if(r.error)throw r.error;entryForm.hidden=true;entryStatus.textContent='Your journal has entered the contest.';await load();}catch(err){entryStatus.textContent=err.message;}finally{submit.disabled=false;}};
 const awards=el('div',undefined,'contest-awards'),community=el('section'),editor=el('section');awards.append(community,editor);area.append(awards);const entries=el('section');entries.id='entries';const heading=el('div',undefined,'contest-entries-heading'),sort=el('select');sort.setAttribute('aria-label','Sort contest entries');for(const [value,label] of [['votes','Most votes'],['new','Newest']]){const o=el('option',label);o.value=value;sort.append(o);}const refresh=el('button','Refresh');refresh.type='button';heading.append(el('h2','Contest entries'),sort,refresh);const grid=el('div',undefined,'contest-grid'),status=el('p','','hint');status.setAttribute('role','status');entries.append(heading,el('p','One vote per signed-in account. You can change your vote until voting closes. Contest votes are separate from journal likes.','hint'),status,grid);area.append(entries);
 let busy=false;function render(){const state=contestState(c);community.replaceChildren(el('h3','🏆 Community Choice'));editor.replaceChildren(el('h3','⭐ Editor’s Pick'));const winners=communityWinners(rows);community.append(el('p',state.finished?(winners.length?winners.map(e=>e.title).join(' · ')+(winners.length>1?' (tie)':''):'No votes cast.'):'Chosen by your votes.'));const pick=rows.find(e=>e.id===c.editor_entry);editor.append(el('p',state.finished&&pick?pick.title:'Chosen by the editor; announced after voting closes.'));entryButton.disabled=!state.entries||rows.some(e=>e.writer_id===viewer?.id);if(!state.entries)entryStatus.textContent='Entries are closed or have not opened yet.';else if(rows.some(e=>e.writer_id===viewer?.id))entryStatus.textContent='You have already entered this contest.';grid.replaceChildren();const ordered=[...rows];if(sort.value==='new')ordered.sort((a,b)=>Date.parse(b.created_at)-Date.parse(a.created_at));for(const a of ordered){const card=el('article',undefined,'contest-entry'),link=el('a');link.href='./?article='+a.article_id;link.append(cover(a),el('h3',a.title));const writer=el('a',undefined,'contest-writer');writer.href='profile.html?user='+a.writer_id;writer.append(avatar(a.display_name,a.avatar_url),el('span',a.display_name));const vote=el('button',mine===a.id?'✓ Your vote':'Vote',mine===a.id?'primary':'');vote.type='button';vote.setAttribute('aria-pressed',String(mine===a.id));vote.disabled=!state.voting||busy;vote.onclick=async()=>{if(!viewer){location.href='login.html';return;}busy=true;render();try{await requireMember();const r=await db.rpc('vote_writing_contest',{target_contest:c.id,target_entry:a.id});if(r.error)throw r.error;status.textContent='Your vote is saved.';await load();}catch(err){status.textContent=err.message;}finally{busy=false;render();}};card.append(link,writer,el('p',Number(a.votes).toLocaleString()+' votes'),vote);grid.append(card);}if(!rows.length)grid.append(el('p','No entries yet. Be the first to enter.'));}
 async function load(){const r=await db.rpc('writing_contest_entries',{target_contest:c.id});if(r.error)throw r.error;rows=r.data||[];if(viewer){const v=await db.from('contest_votes').select('entry_id').eq('contest_id',c.id).eq('user_id',viewer.id).maybeSingle();if(v.error)throw v.error;mine=v.data?.entry_id||null;}render();}
 sort.onchange=render;refresh.onclick=async()=>{refresh.disabled=true;try{const r=await db.from('writing_contests').select('*').eq('id',c.id).eq('visible',true).single();if(r.error)throw Error('Contest no longer available.');Object.assign(c,r.data);await load();status.textContent='Entries refreshed.';}catch(err){status.textContent=err.message;}finally{refresh.disabled=false;}};await load();if(new URLSearchParams(location.search).has('enter')&&contestState(c).entries)await entryButton.onclick();if(location.hash==='#entries')entries.scrollIntoView();
 }}catch(err){notice.textContent='Contest could not load: '+err.message;}


