import {database,el,config} from './shared.js';
const workspace=document.querySelector('#workspace'),panel=el('section',undefined,'panel contest-admin'),status=el('p','','hint'),list=el('div'),form=el('form'),refresh=el('button','Refresh contests'),add=el('button','New contest');refresh.type=add.type='button';status.setAttribute('role','status');panel.append(el('h2','Contest management'),el('p','Only visible contests appear publicly. The homepage shows the most recently created visible contest. Deadlines use your browser’s local time.','hint'),refresh,add,status,list,form);workspace.append(panel);let db,contests=[],editing=null;
const inputs={};function field(name,label,type='text',max){const wrap=el('label',label),input=el(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;input.name=name;if(max)input.maxLength=max;if(type==='textarea')input.rows=3;wrap.append(input);form.append(wrap);inputs[name]=input;return input;}
field('title','Contest title','text',180).required=true;field('description','Prompt / description','textarea',2000);field('languages','Languages','text',200);field('rules','Rules (include originality, judging criteria, ties, eligibility, and recognition)','textarea',4000);field('recognition','Prize or recognition','text',500);for(const [key,label] of [['starts_at','Opens'],['entries_close','Entries close'],['voting_close','Voting closes']])field(key,label,'datetime-local').required=true;for(const [key,label] of [['visible','Show contest publicly'],['entries_open','Allow entries until deadline'],['voting_open','Allow voting until deadline']])field(key,label,'checkbox');
const pickLabel=el('label','Editor’s Pick (announced after voting ends)'),pick=el('select');pickLabel.append(pick);form.append(pickLabel);const removeEntry=el('button','Remove selected contest entry','danger');removeEntry.type='button';removeEntry.onclick=async()=>{if(!editing||!pick.value)return;if(!confirm('Remove this entry and its contest votes? Its journal will remain.'))return;removeEntry.disabled=true;try{await authorized();const result=await db.from('contest_entries').delete().eq('id',pick.value).eq('contest_id',editing).select('id').single();if(result.error)throw result.error;const fresh=await db.from('writing_contests').select('*').eq('id',editing).single();if(fresh.error)throw fresh.error;await open(fresh.data);status.textContent='Contest entry removed. Journal preserved.';}catch(err){status.textContent=err.message;}finally{removeEntry.disabled=false;}};form.append(removeEntry);const save=el('button','Save contest','primary');save.type='submit';form.append(save);form.hidden=true;
function localDate(value){const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
async function authorized(){db=await database();const r=await db.auth.getUser();if(r.data.user?.id!==config.adminUserId)throw Error('Admin access required.');}
async function open(c=null){await authorized();editing=c?.id||null;form.hidden=false;const now=Date.now(),defaults={title:'',description:'',languages:'Hindi, Urdu, English',rules:'One original journal per writer. One vote per signed-in account. Community Choice goes to the entry with the most votes; equal highest totals share the award. Editor’s Pick is chosen for relevance to the prompt, originality, and quality of writing. No cash prize.',recognition:'Featured on the homepage',starts_at:new Date(now).toISOString(),entries_close:new Date(now+7*86400000).toISOString(),voting_close:new Date(now+10*86400000).toISOString(),visible:false,entries_open:true,voting_open:true};for(const [key,input] of Object.entries(inputs)){const value=c?.[key]??defaults[key];if(input.type==='checkbox')input.checked=Boolean(value);else input.value=input.type==='datetime-local'?localDate(value):value;}pick.replaceChildren();const none=el('option','Not selected');none.value='';pick.append(none);if(c){const r=await db.rpc('writing_contest_entries',{target_contest:c.id});if(r.error)throw r.error;for(const e of r.data){const o=el('option',e.title+' — '+e.display_name);o.value=e.id;pick.append(o);}pick.value=c.editor_entry||'';}form.scrollIntoView({behavior:'smooth'});}
async function load(){refresh.disabled=true;try{await authorized();const r=await db.from('writing_contests').select('*').order('created_at',{ascending:false});if(r.error)throw r.error;contests=r.data;list.replaceChildren();for(const c of contests){const row=el('div',undefined,'contest-row');row.append(el('strong',c.title),el('p',c.visible?'Visible':'Hidden','hint'));const actions=el('div',undefined,'actions');for(const [label,act] of [['Edit',()=>open(c)],[c.visible?'Hide':'Show',()=>update(c,{visible:!c.visible})],['Close entries',()=>update(c,{entries_open:false})],['Close voting',()=>update(c,{voting_open:false})],['Remove contest',async()=>{if(!confirm('Remove this contest, its entries and votes? The journals themselves will remain.'))return;await authorized();const r=await db.from('writing_contests').delete().eq('id',c.id).select('id').single();if(r.error)throw r.error;if(editing===c.id){form.hidden=true;editing=null;}await load();}]]){const b=el('button',label);b.type='button';b.onclick=async()=>{b.disabled=true;try{await act();}catch(err){status.textContent=err.message;}finally{b.disabled=false;}};actions.append(b);}const link=el('a','Preview contest','article-view');link.href='contest.html?id='+c.id;actions.append(link);row.append(actions);list.append(row);}status.textContent=contests.length?'':'No contests yet. Create one to begin.';}catch(err){status.textContent='Contests could not load: '+err.message;}finally{refresh.disabled=false;}}
async function update(c,payload){await authorized();const r=await db.from('writing_contests').update(payload).eq('id',c.id).select('id').single();if(r.error)throw r.error;await load();}
form.onsubmit=async e=>{e.preventDefault();save.disabled=true;try{await authorized();const payload={};for(const [key,input] of Object.entries(inputs))payload[key]=input.type==='checkbox'?input.checked:input.type==='datetime-local'?new Date(input.value).toISOString():input.value.trim();if(Date.parse(payload.entries_close)<=Date.parse(payload.starts_at)||Date.parse(payload.voting_close)<Date.parse(payload.entries_close))throw Error('Entries must close after opening; voting must close on or after entries close.');payload.editor_entry=pick.value||null;const q=editing?db.from('writing_contests').update(payload).eq('id',editing):db.from('writing_contests').insert(payload);const r=await q.select('*').single();if(r.error)throw r.error;editing=r.data.id;await load();status.textContent='Contest saved.';}catch(err){status.textContent=err.message;}finally{save.disabled=false;}};
add.onclick=()=>open().catch(err=>status.textContent=err.message);refresh.onclick=load;new MutationObserver(()=>{if(!workspace.hidden)load();else{list.replaceChildren();form.hidden=true;}}).observe(workspace,{attributes:true,attributeFilter:['hidden']});if(!workspace.hidden)load();


