import {database,el,configured} from './shared.js';
async function guest(db){const {data,error}=await db.auth.getSession();if(error)throw error;if(data.session)return data.session.user;const result=await db.auth.signInAnonymously();if(result.error)throw result.error;return result.data.user;}
export async function mountEngagement(article,parent){
 const section=el('section',undefined,'engagement');section.append(el('h2','Join the conversation'));parent.append(section);
 if(!configured||article.id.startsWith('sample-')){section.append(el('p','Reactions and comments will be available for published articles.'));return;}
 const feedback=el('p','','hint');feedback.setAttribute('role','status');feedback.setAttribute('aria-live','polite');
 const reactions=el('div',undefined,'reaction-buttons');const like=el('button','Like'),dislike=el('button','Dislike');like.type=dislike.type='button';reactions.append(like,dislike);
 const heading=el('h3','Comments'),list=el('div',undefined,'comments-list');
 const form=el('form',undefined,'comment-form');const nameLabel=el('label','Your name'),name=el('input');name.required=true;name.maxLength=60;name.autocomplete='name';nameLabel.append(name);
 const bodyLabel=el('label','Your comment'),body=el('textarea');body.required=true;body.maxLength=2000;body.rows=4;bodyLabel.append(body);
 const send=el('button','Submit comment','primary');send.type='submit';form.append(nameLabel,bodyLabel,el('p','Comments appear after approval.','hint'),send);
 section.append(reactions,feedback,heading,list,form);let db,mine=0;
 function selection(){like.setAttribute('aria-pressed',String(mine===1));dislike.setAttribute('aria-pressed',String(mine===-1));}
 async function counts(){const {data,error}=await db.rpc('article_reaction_counts',{target_article:article.id});if(error)throw error;like.textContent='Like · '+(data?.[0]?.likes||0);dislike.textContent='Dislike · '+(data?.[0]?.dislikes||0);selection();}
 async function comments(){const {data,error}=await db.from('article_comments').select('id,name,body,created_at').eq('article_id',article.id).eq('approved',true).order('created_at',{ascending:false}).limit(100);if(error)throw error;list.replaceChildren();heading.textContent='Comments'+(data.length?' ('+data.length+')':'');if(!data.length)list.append(el('p','Be the first to share a thought.','hint'));for(const c of data){const item=el('article',undefined,'comment');item.append(el('strong',c.name),el('small',new Date(c.created_at).toLocaleDateString()),el('p',c.body));list.append(item);}}
 async function react(value){like.disabled=dislike.disabled=true;try{const user=await guest(db);const read=await db.from('article_reactions').select('value').eq('article_id',article.id).eq('user_id',user.id).maybeSingle();if(read.error)throw read.error;mine=read.data?.value||0;const next=mine===value?0:value;const result=next?await db.from('article_reactions').upsert({article_id:article.id,user_id:user.id,value:next}):await db.from('article_reactions').delete().eq('article_id',article.id).eq('user_id',user.id);if(result.error)throw result.error;mine=next;await counts();feedback.textContent=next?'Thanks for your feedback.':'Reaction removed.';}catch(err){feedback.textContent='Could not save your reaction: '+err.message;}finally{like.disabled=dislike.disabled=false;}}
 like.onclick=()=>react(1);dislike.onclick=()=>react(-1);
 form.onsubmit=async e=>{e.preventDefault();send.disabled=true;try{if(!name.value.trim()||!body.value.trim())throw Error('Enter your name and comment.');await guest(db);const {error}=await db.from('article_comments').insert({article_id:article.id,name:name.value.trim(),body:body.value.trim()});if(error)throw error;form.reset();feedback.textContent='Thank you! Your comment is waiting for approval.';}catch(err){feedback.textContent='Could not send your comment: '+err.message;}finally{send.disabled=false;}};
 try{db=await database();const {data}=await db.auth.getSession();if(data.session){const result=await db.from('article_reactions').select('value').eq('article_id',article.id).eq('user_id',data.session.user.id).maybeSingle();if(result.error)throw result.error;mine=result.data?.value||0;}await counts();await comments();}catch{feedback.textContent='Reactions and comments are temporarily unavailable.';like.disabled=dislike.disabled=send.disabled=true;}
}
