import {database,el,configured} from './shared.js';
import {requireMember,member,profile} from './member-auth.js';
async function guest(){return requireMember();}
export async function mountEngagement(article,parent){
 const section=el('section',undefined,'engagement');section.append(el('h2','Join the conversation'));parent.append(section);
 if(!configured||article.id.startsWith('sample-')){section.append(el('p','Reactions and comments will be available for published articles.'));return;}
 const feedback=el('p','','hint');feedback.setAttribute('role','status');feedback.setAttribute('aria-live','polite');
 const reactions=el('div',undefined,'reaction-buttons');const like=el('button','Like'),dislike=el('button','Dislike');like.type=dislike.type='button';reactions.append(like,dislike);
 const heading=el('h3','Comments'),list=el('div',undefined,'comments-list');
 const form=el('form',undefined,'comment-form');const nameLabel=el('label','Your name'),name=el('input');name.required=true;name.maxLength=60;name.autocomplete='name';nameLabel.append(name);
 const bodyLabel=el('label','Your comment'),body=el('textarea');body.required=true;body.maxLength=2000;body.rows=4;bodyLabel.append(body);
 name.readOnly=true;
 const send=el('button','Post comment','primary');send.type='submit';form.append(nameLabel,bodyLabel,el('p','Comments are published immediately. Please keep the conversation respectful.','hint'),send);
 const signin=el('a','Sign in with Google to react or comment.','article-view');signin.href='account.html';signin.hidden=true;
 section.append(reactions,signin,feedback,heading,list,form);let db,mine=0,viewer=null;
 function selection(){like.setAttribute('aria-pressed',String(mine===1));dislike.setAttribute('aria-pressed',String(mine===-1));}
 async function counts(){const {data,error}=await db.rpc('article_reaction_counts',{target_article:article.id});if(error)throw error;like.textContent='Like · '+(data?.[0]?.likes||0);dislike.textContent='Dislike · '+(data?.[0]?.dislikes||0);selection();}
 async function comments(){const {data,error}=await db.from('article_comments').select('id,name,body,created_at,user_id').eq('article_id',article.id).eq('approved',true).order('created_at',{ascending:false}).limit(100);if(error)throw error;list.replaceChildren();heading.textContent='Comments'+(data.length?' ('+data.length+')':'');if(!data.length)list.append(el('p','Be the first to share a thought.','hint'));for(const c of data){const item=el('article',undefined,'comment');const author=el('a',c.name);author.href='profile.html?user='+c.user_id;item.append(author,el('small',new Date(c.created_at).toLocaleDateString()),el('p',c.body));if(viewer&&(viewer.id===c.user_id||viewer.id===article.owner_id||viewer.id===window.OFFICELIFE_CONFIG.adminUserId)){const remove=el('button','Delete comment','danger');remove.type='button';remove.onclick=async()=>{if(!confirm('Permanently delete this comment?'))return;remove.disabled=true;try{await requireMember();const {error}=await db.from('article_comments').delete().eq('id',c.id).select('id').single();if(error)throw error;await comments();feedback.textContent='Comment deleted.';}catch(err){feedback.textContent=err.message;remove.disabled=false;}};item.append(remove);}list.append(item);}}
 async function react(value){like.disabled=dislike.disabled=true;try{const user=await guest(db);const read=await db.from('article_reactions').select('value').eq('article_id',article.id).eq('user_id',user.id).maybeSingle();if(read.error)throw read.error;mine=read.data?.value||0;const next=mine===value?0:value;const result=next?await db.from('article_reactions').upsert({article_id:article.id,user_id:user.id,value:next}):await db.from('article_reactions').delete().eq('article_id',article.id).eq('user_id',user.id);if(result.error)throw result.error;mine=next;await counts();feedback.textContent=next?'Thanks for your feedback.':'Reaction removed.';}catch(err){feedback.textContent='Could not save your reaction: '+err.message;}finally{like.disabled=dislike.disabled=false;}}
 like.onclick=()=>react(1);dislike.onclick=()=>react(-1);
 form.onsubmit=async e=>{e.preventDefault();send.disabled=true;try{if(!body.value.trim())throw Error('Enter your comment.');await requireMember();const p=await profile();const {error}=await db.from('article_comments').insert({article_id:article.id,name:p.display_name,body:body.value.trim()});if(error)throw error;body.value='';await comments();feedback.textContent='Your comment is published.';}catch(err){feedback.textContent='Could not send your comment: '+err.message;}finally{send.disabled=false;}};
 try{db=await database();viewer=await member();if(viewer){const p=await profile();name.value=p.display_name;const result=await db.from('article_reactions').select('value').eq('article_id',article.id).eq('user_id',viewer.id).maybeSingle();if(result.error)throw result.error;mine=result.data?.value||0;}else{signin.hidden=false;form.hidden=true;like.disabled=dislike.disabled=true;}await counts();await comments();}catch{feedback.textContent='Reactions and comments are temporarily unavailable.';like.disabled=dislike.disabled=send.disabled=true;}
}
