import {database,el,config} from './shared.js';
const workspace=document.querySelector('#workspace'),panel=el('section',undefined,'panel featured-admin'),status=el('p','','hint'),label=el('label','Published journal'),select=el('select'),save=el('button','Set featured journal','primary'),remove=el('button','Remove from homepage'),refresh=el('button','Refresh journals'),preview=el('a','View homepage','article-view');
status.setAttribute('role','status');label.append(select);preview.href='./';preview.target='_blank';preview.rel='noopener';const actions=el('div',undefined,'actions');actions.append(save,remove,refresh,preview);panel.append(el('h2','Featured journal'),el('p','Choose the journal shown at the top of the homepage. Removing the feature keeps the journal published.','hint'),label,actions,status);workspace.append(panel);let db,loading=false,ready=false;
async function authorized(){db=await database();const auth=await db.auth.getUser();if(auth.error||auth.data.user?.id!==config.adminUserId)throw Error('Admin access required.');}
function busy(value){loading=value;select.disabled=save.disabled=remove.disabled=refresh.disabled=value;}
async function load(){busy(true);ready=false;try{await authorized();const results=await Promise.all([db.from('articles').select('id,title,author,profiles!articles_owner_id_fkey(display_name)').eq('status','published').order('published_at',{ascending:false}),db.from('homepage_feature').select('article_id').eq('id',true).maybeSingle()]);for(const r of results)if(r.error)throw r.error;select.replaceChildren();const none=el('option','No featured journal');none.value='';select.append(none);for(const a of results[0].data){const option=el('option',a.title+' — '+(a.profiles?.display_name||a.author));option.value=a.id;select.append(option);}const current=results[1].data?.article_id;select.value=results[0].data.some(a=>a.id===current)?current:'';status.textContent=select.value?'A journal is featured. Choose another and save to replace it.':'No published journal is currently featured.';ready=true;}catch(e){status.textContent='Featured journal controls could not load. Run featured-journal.sql in Supabase, then refresh. '+e.message;}finally{busy(false);save.disabled=remove.disabled=!ready;}}
async function update(id){if(loading||!ready)return;busy(true);try{await authorized();const r=await db.rpc('set_homepage_featured_journal',{target_article:id||null});if(r.error)throw r.error;await load();status.textContent=id?'Featured journal updated. Refresh the homepage to see it.':'Featured journal removed from the homepage. The journal remains published.';}catch(e){status.textContent='Could not update: '+e.message;}finally{busy(false);save.disabled=remove.disabled=!ready;}}
save.onclick=()=>update(select.value);remove.onclick=()=>update(null);refresh.onclick=load;let visible=false;
function visibility(){if(!workspace.hidden&&!visible){visible=true;load();}if(workspace.hidden){visible=false;ready=false;select.replaceChildren();status.textContent='';}}
new MutationObserver(visibility).observe(workspace,{attributes:true,attributeFilter:['hidden']});visibility();
