import {database,el} from './shared.js';import {requireMember,profile} from './member-auth.js';
export const MAX_PHOTO_SIZE=2097152;
export async function validatePhoto(file){if(!file||!file.size)throw Error('Choose a JPG or PNG image.');if(file.size>MAX_PHOTO_SIZE)throw Error('Your image must be 2 MB or smaller.');const ext=file.name.split('.').pop().toLowerCase();if(!['jpg','png'].includes(ext))throw Error('Only .jpg and .png files are accepted.');const mime=ext==='jpg'?'image/jpeg':'image/png';if(file.type&&file.type!==mime)throw Error('The image type does not match its extension.');const bytes=new Uint8Array(await file.slice(0,8).arrayBuffer());const valid=ext==='jpg'?bytes[0]===255&&bytes[1]===216&&bytes[2]===255:[137,80,78,71,13,10,26,10].every((b,i)=>bytes[i]===b);if(!valid)throw Error('This file is not a valid JPG or PNG image.');return {ext,mime};}
export async function cleanOldPhotos(db,userId){const r=await db.from('profile_photo_cleanup').select('path').eq('user_id',userId);if(r.error)throw r.error;for(const row of r.data){const current=await db.from('profiles').select('avatar_storage_path').eq('id',userId).single();if(current.error)throw current.error;if(current.data.avatar_storage_path===row.path)continue;const removal=await db.storage.from('profile-photos').remove([row.path]);if(removal.error)throw removal.error;const done=await db.from('profile_photo_cleanup').delete().eq('user_id',userId).eq('path',row.path);if(done.error)throw done.error;}}
export async function changePhoto(db,userId,file,current){const info=file?await validatePhoto(file):null;let path=null;if(file){path=userId+'/'+crypto.randomUUID()+'.'+info.ext;const upload=await db.storage.from('profile-photos').upload(path,file,{contentType:info.mime,upsert:false,cacheControl:'3600'});if(upload.error)throw upload.error;}const result=await db.rpc('replace_profile_photo',{new_path:path,expected_path:current.avatar_storage_path||null});if(result.error){if(path){const check=await db.from('profiles').select('avatar_storage_path').eq('id',userId).single();if(!check.error&&check.data.avatar_storage_path!==path)await db.storage.from('profile-photos').remove([path]);}throw result.error;}let cleanupPending=false;try{await cleanOldPhotos(db,userId);}catch{cleanupPending=true;}return {profile:result.data,cleanupPending};}
export function photoControls(onSaved){const box=el('div',undefined,'photo-controls'),file=el('input'),label=el('label','Edit profile picture'),remove=el('button','Remove picture'),feedback=el('p','','hint');file.type='file';file.accept='.jpg,.png';file.setAttribute('aria-label','Upload JPG or PNG profile picture');label.append(file);remove.type='button';feedback.setAttribute('role','status');box.append(label,el('p','JPG or PNG · Maximum 2 MB. Your profile picture is public.','hint'),remove,feedback);let busy=false;
async function save(upload){if(busy)return;busy=true;file.disabled=remove.disabled=true;feedback.textContent=upload?'Uploading your picture…':'Removing your picture…';try{const user=await requireMember(),db=await database(),current=await profile();const result=await changePhoto(db,user.id,upload,current);await onSaved(result.profile);document.dispatchEvent(new CustomEvent('profile-photo-changed',{detail:result.profile}));feedback.textContent=result.cleanupPending?'Picture saved. Previous image cleanup will retry next time you open this page.':upload?'Profile picture updated. Previous uploaded picture deleted.':'Picture removed. Your name initial will appear.';}catch(err){feedback.textContent=err.message;}finally{file.value='';busy=false;file.disabled=remove.disabled=false;}}
file.onchange=()=>{if(file.files?.[0])save(file.files[0]);};remove.onclick=()=>{if(confirm('Remove your current profile picture?'))save(null);};
(async()=>{try{const u=await requireMember();await cleanOldPhotos(await database(),u.id);}catch{}})();return box;}
