import {reportButton} from './reporting.js';
import {database,el,safeImage} from './shared.js';
import {member,requireMember} from './member-auth.js';
export const choices=[['like','❤️','Like']];
export function avatar(name,url,size=''){const box=el('span',undefined,'user-avatar '+size);const first=Array.from((name||'Member').trim())[0]||'M';box.textContent=first.toLocaleUpperCase();box.setAttribute('aria-label',name||'Member');if(safeImage(url)){const img=el('img');img.src=url;img.alt='';img.referrerPolicy='no-referrer';img.onerror=()=>img.remove();box.append(img);}return box;}
export async function writerHeader(a,p={}){const row=el('div',undefined,'writer-header');const link=el('a',undefined,'writer-link');link.href=a.owner_id?'profile.html?user='+a.owner_id:'./';link.append(avatar(p.display_name||a.author,p.avatar_url));const text=el('span');text.append(el('strong',p.display_name||a.author),el('small',new Date(a.published_at).toLocaleDateString('en',{month:'short',day:'numeric',year:'numeric'})));link.append(text);row.append(link);if(a.owner_id)row.append(await followButton(a.owner_id));return row;}
export async function followButton(id){const button=el('button','Follow','follow-button');button.type='button';let following=false;let viewer;const sync=()=>{button.textContent=following?'Following':'Follow';button.setAttribute('aria-pressed',String(following));};try{viewer=await member();if(viewer?.id===id){button.hidden=true;return button;}if(viewer){const db=await database();const result=await db.from('profile_follows').select('followed_id').eq('follower_id',viewer.id).eq('followed_id',id).maybeSingle();if(result.error)throw result.error;following=Boolean(result.data);sync();}}catch{button.disabled=true;button.title='Follow is unavailable until the database update is installed.';}
button.onclick=async()=>{if(!viewer){location.href='account.html';return;}button.disabled=true;try{viewer=await requireMember();const db=await database();const result=following?await db.from('profile_follows').delete().eq('follower_id',viewer.id).eq('followed_id',id):await db.from('profile_follows').insert({follower_id:viewer.id,followed_id:id});if(result.error)throw result.error;following=!following;sync();document.dispatchEvent(new CustomEvent('journal-follow',{detail:{id,following}}));}catch(err){button.title=err.message;button.textContent='Try again';}finally{button.disabled=false;}};
document.addEventListener('journal-follow',e=>{if(e.detail.id===id){following=e.detail.following;sync();}});return button;}
const iconPaths={react:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z',view:'M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Zm13 0a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',comment:'M21 11a8 8 0 0 1-8 8H7l-4 3V11a9 9 0 0 1 18 0Z',share:'M14 3l7 7-7 7v-4c-5 0-9 2-11 6 0-7 4-12 11-12V3'};
function action(name,label){const b=el('button',undefined,'social-action');b.type='button';const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',iconPaths[name]);svg.append(path);b.append(svg,el('span',label));return b;}
export async function socialActions(a,parent,onComment){const box=el('div',undefined,'social-block'),summary=el('p','Loading likes…','social-summary'),bar=el('div',undefined,'social-bar'),react=action('react','Like'),comment=action('comment','Comment'),share=action('share','Share'),views=action('view','0'),picker=el('div',undefined,'reaction-picker'),status=el('p','','social-status');status.setAttribute('role','status');status.setAttribute('aria-live','polite');picker.hidden=true;picker.setAttribute('role','group');picker.setAttribute('aria-label','Choose a reaction');react.setAttribute('aria-expanded','false');views.className='view-count';views.disabled=true;bar.append(react,comment,share,views);box.append(summary,picker,bar,status,reportButton(a.id));parent.append(box);let db,viewer,mine=null;const optionButtons=[];
const close=()=>{picker.hidden=true;react.setAttribute('aria-expanded','false');};
async function load(){const result=await db.rpc('journal_social_summary',{target_article:a.id});if(result.error)throw result.error;const s=result.data||{};views.querySelector('span').textContent=new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(Number(s.views)||0).toLowerCase();views.setAttribute('aria-label',(Number(s.views)||0)+' views');views.title=(Number(s.views)||0)+' views';summary.replaceChildren(reactionSummaryNode(s,mine),el('span',(s.comments||0)+' '+(Number(s.comments)===1?'comment':'comments')));summary.title=choices.map(([k,,label])=>label+': '+(s.kinds?.[k]||0)).join(' · ');react.querySelector('span').textContent=new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(Number(s.reactions)||0).toLowerCase();comment.querySelector('span').textContent=new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(Number(s.comments)||0).toLowerCase();comment.setAttribute('aria-label',(Number(s.comments)||0)+' comments; open comments');react.classList.toggle('selected',Boolean(mine));react.setAttribute('aria-pressed',String(Boolean(mine)));react.setAttribute('aria-label',mine?'Remove like':'Like journal');for(const [kind,b] of optionButtons)b.setAttribute('aria-pressed',String(kind===mine));}
for(const [kind,emoji,label] of choices){const b=el('button',emoji);b.type='button';b.title=label;b.setAttribute('aria-label',label);optionButtons.push([kind,b]);b.onclick=async()=>{optionButtons.forEach(([,n])=>n.disabled=true);try{viewer=await requireMember();const current=await db.from('article_reactions').select('kind').eq('article_id',a.id).eq('user_id',viewer.id).maybeSingle();if(current.error)throw current.error;const next=current.data?.kind===kind?null:kind;const result=next?await db.from('article_reactions').upsert({article_id:a.id,user_id:viewer.id,value:1,kind:next}):await db.from('article_reactions').delete().eq('article_id',a.id).eq('user_id',viewer.id);if(result.error)throw result.error;mine=next;close();await load();status.textContent='';}catch(err){status.textContent=err.message;}finally{optionButtons.forEach(([,n])=>n.disabled=false);}};picker.append(b);}
react.onclick=async()=>{if(!viewer){location.href='login.html';return;}if(react.disabled)return;react.disabled=true;try{await optionButtons[0][1].onclick();}finally{react.disabled=false;}};box.addEventListener('keydown',e=>{if(e.key==='Escape'){close();react.focus();}});document.addEventListener('click',e=>{if(!box.contains(e.target))close();});
const url=new URL('./?article='+encodeURIComponent(a.id),location.href).href;comment.onclick=()=>{if(onComment)onComment();else location.href=url+'#comments';};share.onclick=async()=>{try{if(navigator.share)await navigator.share({title:a.title,url});else{await navigator.clipboard.writeText(url);status.textContent='Journal link copied.';}}catch(err){if(err.name!=='AbortError'){status.replaceChildren(el('span','Copy this journal link: '));const input=el('input');input.readOnly=true;input.value=url;status.append(input);input.focus();input.select();}}};
document.addEventListener('journal-comments',e=>{if(e.detail===a.id)load().catch(()=>{});});
try{db=await database();viewer=await member();if(viewer){const result=await db.from('article_reactions').select('kind').eq('article_id',a.id).eq('user_id',viewer.id).maybeSingle();if(result.error)throw result.error;mine=result.data?.kind||null;}await load();}catch{summary.textContent='Likes are temporarily unavailable.';react.disabled=true;}return box;}

export function formatReactionSummary(summary){const kinds=summary.kinds||{};const emojis=choices.filter(([kind])=>Number(kinds[kind]||0)>0).sort((a,b)=>Number(kinds[b[0]])-Number(kinds[a[0]])).map(([,emoji])=>emoji).join('');return (emojis?emojis+' ':'')+Number(summary.reactions||0).toLocaleString();}

export function reactionCountLabel(total,mine){const count=Math.max(0,Number(total)||0),short=n=>n>=1000?new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(n).toLowerCase():String(n);return mine&&count>0?(count===1?'You':'You + '+short(count-1)):short(count);}
function reactionSummaryNode(summary,mine){const group=el('span',undefined,'reaction-total'),icons=el('span',undefined,'reaction-icons'),kinds=summary.kinds||{};const ranked=choices.filter(([kind])=>Number(kinds[kind]||0)>0).sort((a,b)=>Number(kinds[b[0]])-Number(kinds[a[0]])).slice(0,3);for(const [kind,emoji,label] of ranked){const bubble=el('span',emoji,'reaction-bubble reaction-'+kind);bubble.setAttribute('aria-hidden','true');bubble.title=label;icons.append(bubble);}group.append(icons,el('span',reactionCountLabel(summary.reactions,mine)));group.setAttribute('aria-label',Number(summary.reactions||0).toLocaleString()+' total likes'+(mine?', including yours':''));return group;}





